In [1]:
import numpy as np
import pandas as pd

In [16]:
# DATA FRAME DE LA SITUACIÓN DE LAS LENGUASE N EL MUNDO

df_lang = pd.read_csv("./extinct_languages.csv")

df_lang.info()

df_lang.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2722 entries, 0 to 2721
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           2722 non-null   int64
 1   Name in English              2722 non-null   object
 2   Name in French               2699 non-null   object
 3   Name in Spanish              2701 non-null   object
 4   Countries                    2721 non-null   object
 5   Country codes alpha 3        2721 non-null   object
 6   ISO639-3 codes               2458 non-null   object
 7   Degree of endangerment       2722 non-null   object
 8   Alternate names              1583 non-null   object
 9   Name in the language         27 non-null     object
 10  Number of speakers           2539 non-null   float64
 11  Sources                      2079 non-null   object
 12  Latitude                     2719 non-null   float64
 13  Longitude                    2719 non-null   float64
 14  Description of the location  1870 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 319.1+ KB

,ID,Name in English,Name in French,Name in Spanish,Countries,Country codes alpha 3,ISO639-3 codes,Degree of endangerment,Alternate names,Name in the language,Number of speakers,Sources,Latitude,Longitude,Description of the location
0,1022,South Italian,italien du sud,napolitano-calabrés,Italy,ITA,nap,Vulnerable,Neapolitan; Neapolitan-Calabrese; неаполитанск...,NaN,7500000.0,NaN,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,sicilien,siciliano,Italy,ITA,scn,Vulnerable,NaN,NaN,5000000.0,NaN,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,bas-saxon,bajo sajón,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS","act, drt, frs, gos, nds, sdz, stl, twd, vel, wep",Vulnerable,"Low German, Niedersächsisch, Nedersaksisch, Ni...",Neddersassisch,4800000.0,NaN,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,biélorusse,bielorruso,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",bel,Vulnerable,NaN,NaN,4000000.0,Hienadź Cychun: Weißrussisch. — Lexikon der Sp...,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,lombard,lombardo,"Italy, Switzerland","ITA, CHE",lmo,Definitely endangered,NaN,NaN,3500000.0,NaN,45.7215,9.3273,the region of Lombardy (except the southernmos...
5,405,Romani,romani,romaní,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...","rmc, rmf, rml, rmn, rmo, rmw, rmy",Definitely endangered,"sinti, vlax, calò",NaN,3500000.0,Yaron Matras: Romani: a linguistic introductio...,46.3165,22.3681,"many European countries, most densely in East-..."
6,2211,Yiddish (Israel),yiddish (Israël),yiddish (Israel),Israel,ISR,ydd,Definitely endangered,Judeo-German,NaN,3000000.0,Neil G. Jacobs: Yiddish: a linguistic introduc...,32.0833,34.8333,"most speakers now live outside Europe, mainly ..."
7,1586,Gondi,gondi,gondí,India,IND,gon,Vulnerable,Gondi; Gaudi; Gondiva; Gondwadi; Goondile; Gou...,NaN,2713790.0,NaN,19.5804,80.4418,"Madhya Pradesh (Betul, Chhindwara, Seoni, Mand..."
8,1020,Limburgian-Ripuarian,francique ripuaire -limbourgeois,limburgués-ripuarino,"Germany, Belgium, Netherlands","DEU, BEL, NLD","ksh, lim",Vulnerable,Colognian (dialect; in German: Kölsch),NaN,2600000.0,NaN,50.7781,6.0864,Limburg provinces in Belgium and the Netherlan...
9,1943,Quechua of Southern Bolivia,quechua bolivien du sud,quechua boliviano meridional,Bolivia (Plurinational State of),BOL,quh,Vulnerable,NaN,NaN,2300000.0,NaN,-18.0675,-65.7641,"Departments of Cochabamba, Chuquisaca, Potosí ..."

In [ ]:
# Eliminar columnas que poco peso o nulo que no vamos a utilizar en nuestro análisis
df_lang = df_lang.drop(['Name in French', 'Name in Spanish', 'Country codes alpha 3', 'ISO639-3 codes', 'Alternate names', 'Name in the language', 'Sources', 'Latitude', 'Longitude'], axis=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2722 entries, 0 to 2721
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           2722 non-null   int64
 1   Name in English              2722 non-null   object
 2   Countries                    2721 non-null   object
 3   Degree of endangerment       2722 non-null   object
 4   Number of speakers           2539 non-null   float64
 5   Description of the location  1870 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 127.7+ KB

In [ ]:
# normalizar el nombre de las columnas restantes
df_lang = df_lang.rename(columns={'Name in English': 'Name_English',
    'Degree of endangerment': 'Degree_endagerment',
    'Number of speakers': 'Number_speakers',
    'Description of the location': 'Description_location'
    }
)

In [ ]:
# creación de una nueva columna con los valroes de endangerment order categorizada
endangerment_order = {
    'Vulnerable': 1,
    'Definitely endangered': 2,
    'Severely endangered': 3,
    'Critically endangered': 4,
    'Extinct': 5
}
df_lang['endangerment_score'] = df_lang['Degree_endagerment'].map(endangerment_order)

df_lang.head(20)

,ID,Name_English,Countries,Degree_endagerment,Number_speakers,Description_location,endangerment_score
0,1022,South Italian,Italy,Vulnerable,7500000.0,"Campania, Lucania (Basilicata), Abruzzi (Abruz...",1
1,1023,Sicilian,Italy,Vulnerable,5000000.0,"Sicily (Sicilia), southern and central Calabri...",1
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",Vulnerable,4000000.0,Belarus except the Polesian-speaking south-wes...,1
4,382,Lombard,"Italy, Switzerland",Definitely endangered,3500000.0,the region of Lombardy (except the southernmos...,2
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...",Definitely endangered,3500000.0,"many European countries, most densely in East-...",2
6,2211,Yiddish (Israel),Israel,Definitely endangered,3000000.0,"most speakers now live outside Europe, mainly ...",2
7,1586,Gondi,India,Vulnerable,2713790.0,"Madhya Pradesh (Betul, Chhindwara, Seoni, Mand...",1
8,1020,Limburgian-Ripuarian,"Germany, Belgium, Netherlands",Vulnerable,2600000.0,Limburg provinces in Belgium and the Netherlan...,1
9,1943,Quechua of Southern Bolivia,Bolivia (Plurinational State of),Vulnerable,2300000.0,"Departments of Cochabamba, Chuquisaca, Potosí ...",1
10,1565,Kumaoni,"India, Nepal",Vulnerable,2003783.0,"Uttarakhand, also in Uttar Pradesh, Madhya Pra...",1
11,755,Aymara,"Bolivia (Plurinational State of), Chile, Peru",Vulnerable,2000000.0,"Departamentos de Puno, Moquegua y Tacna, en ...",1
12,349,Emilian-Romagnol,"Italy, San Marino",Definitely endangered,2000000.0,"the region of Emilia-Romagna, parts of the pro...",2
13,399,Piedmontese,Italy,Definitely endangered,2000000.0,"Piedmont Region except the Novara Province, th...",2
14,1021,Venetan,"Croatia, Italy, Slovenia",Vulnerable,2000000.0,"Veneto region, parts of Friuli-Venezia Giulia,...",1
15,1985,Zazaki,Turkey,Vulnerable,2000000.0,"Tunceli, Erzincan, Elazığ and Bingöl provinces...",1
16,1591,Kurux (India),India,Vulnerable,1751489.0,Jharkhand and Bihar,1
17,2065,Tamajeq,Niger,Vulnerable,1750000.0,NaN,1
18,1585,Tulu,India,Vulnerable,1722768.0,"Karnataka, Andhra Pradesh, Kerala",1
19,1556,Kangdi,India,Definitely endangered,1700000.0,Himachal Pradesh,2

In [ ]:
df_count = pd.read_csv("../data/countries of the world.csv")

df_count.info()

df_count.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Country                             227 non-null    str
 1   Region                              227 non-null    str
 2   Population                          227 non-null    int64
 3   Area (sq. mi.)                      227 non-null    int64
 4   Pop. Density (per sq. mi.)          227 non-null    str
 5   Coastline (coast/area ratio)        227 non-null    str
 6   Net migration                       224 non-null    str
 7   Infant mortality (per 1000 births)  224 non-null    str
 8   GDP ($ per capita)                  226 non-null    float64
 9   Literacy (%)                        209 non-null    str
 10  Phones (per 1000)                   223 non-null    str
 11  Arable (%)                          225 non-null    str
 12  Crops (%)                           225 non-null    str
 13  Other (%)                           225 non-null    str
 14  Climate                             205 non-null    str
 15  Birthrate                           224 non-null    str
 16  Deathrate                           223 non-null    str
 17  Agriculture                         212 non-null    str
 18  Industry                            211 non-null    str
 19  Service                             212 non-null    str
dtypes: float64(1), int64(2), str(17)
memory usage: 35.6 KB

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN
5,Angola,SUB-SAHARAN AFRICA,12127071,1246700,"9,7","0,13",0,"191,19",1900.0,"42,0","7,8","2,41","0,24","97,35",NaN,"45,11","24,2","0,096","0,658","0,246"
6,Anguilla,LATIN AMER. & CARIB,13477,102,"132,1","59,80","10,76","21,03",8600.0,"95,0","460,0",0,0,100,2,"14,17","5,34","0,04","0,18","0,78"
7,Antigua & Barbuda,LATIN AMER. & CARIB,69108,443,"156,0","34,54","-6,15","19,46",11000.0,"89,0","549,9","18,18","4,55","77,27",2,"16,93","5,37","0,038","0,22","0,743"
8,Argentina,LATIN AMER. & CARIB,39921833,2766890,"14,4","0,18","0,61","15,18",11200.0,"97,1","220,4","12,31","0,48","87,21",3,"16,73","7,55","0,095","0,358","0,547"
9,Armenia,C.W. OF IND. STATES,2976372,29800,"99,9","0,00","-6,47","23,28",3500.0,"98,6","195,7","17,55","2,3","80,15",4,"12,07","8,23","0,239","0,343","0,418"